package com.example.pronunciation.speech;

import android.content.Context;
import android.util.Log;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Word to IPA phoneme lookup, backed by a CMUdict-derived table bundled at build time.
 *
 * <p>Format is one entry per line: {@code word<TAB>p1 p2 p3}. Generated by
 * {@code tools/prepare_assets.py}, which also maps ARPAbet to the IPA inventory the model emits —
 * the two must agree or every comparison scores zero.
 */
public class Lexicon {

    private static final String TAG = "Lexicon";
    private static final String LEXICON_ASSET = "lexicon.txt";

    private final Map<String, String[]> entries = new HashMap<>(140_000);
    private volatile boolean loaded = false;

    /** Blocking; ~1-2 s for the full dictionary. Call from a worker thread. */
    public boolean load(Context context) {
        if (loaded) return true;
        try (InputStream in = context.getAssets().open(LEXICON_ASSET);
             BufferedReader reader = new BufferedReader(
                     new InputStreamReader(in, StandardCharsets.UTF_8), 64 * 1024)) {

            String line;
            while ((line = reader.readLine()) != null) {
                int tab = line.indexOf('\t');
                if (tab <= 0) continue;

                String word = line.substring(0, tab).toLowerCase(Locale.ROOT);
                String[] phonemes = line.substring(tab + 1).trim().split("\\s+");
                if (phonemes.length > 0 && !phonemes[0].isEmpty()) {
                    entries.put(word, phonemes);
                }
            }
            loaded = true;
            Log.i(TAG, "Loaded " + entries.size() + " lexicon entries");
            return true;
        } catch (IOException e) {
            Log.e(TAG, "Failed to load " + LEXICON_ASSET, e);
            return false;
        }
    }

    public boolean isLoaded() {
        return loaded;
    }

    /** Builds a lexicon from an in-memory map — used by unit tests, which have no assets. */
    public static Lexicon inMemory(Map<String, String[]> words) {
        Lexicon lexicon = new Lexicon();
        for (Map.Entry<String, String[]> entry : words.entrySet()) {
            lexicon.entries.put(normalize(entry.getKey()), entry.getValue());
        }
        lexicon.loaded = true;
        return lexicon;
    }

    /** @return phonemes for the word, or null if it is not in the dictionary */
    public String[] lookup(String word) {
        return entries.get(normalize(word));
    }

    /** Splits text into words as they should be scored, keeping the original spelling for display. */
    public static List<String> tokenize(String text) {
        List<String> words = new ArrayList<>();
        for (String raw : text.split("\\s+")) {
            String cleaned = normalize(raw);
            if (!cleaned.isEmpty()) words.add(raw);
        }
        return words;
    }

    /**
     * Lowercase, strip surrounding punctuation, keep internal apostrophes and hyphens.
     *
     * <p>{@link Locale#ROOT} is not optional here. The device locale would apply Turkish casing
     * on a tr-TR phone, turning "I" into "ı" — which then fails both the dictionary lookup and
     * the {@code [^a-z']} filter, silently dropping the word from scoring. This dictionary is
     * ASCII English regardless of who is holding the phone.
     */
    public static String normalize(String word) {
        return word.toLowerCase(Locale.ROOT)
                .replaceAll("^[^a-z']+", "")
                .replaceAll("[^a-z']+$", "");
    }
}
