#!/usr/bin/env python3
"""Generate the Mandarin practice corpus.

    python tools/generate_content_zh.py

Writes, into app/src/main/assets/:
    prompts_zh.tsv        unit, hanzi, pinyin, focus
    game_problems_zh.tsv  level, title, pinyin, paragraphs joined by ||
    zh_syllables.tsv      the initials/finals table that replaces the A-Z section

Every prompt carries its pinyin, generated by pypinyin over the *whole* sentence so
context-sensitive readings (不 bù/bú, 一 yī/yí/yì, 了 le/liǎo) come out right. Looking each
character up in isolation would get those wrong, and a learner reading the wrong tone off the
screen is worse than no pinyin at all.
"""

from __future__ import annotations

import random
import sys
from collections import Counter
from pathlib import Path

try:
    from pypinyin import Style, pinyin
except ImportError:
    sys.exit("pip install pypinyin")

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "app/src/main/assets"

SEED = 20260821
TARGET_WORDS = 320
TARGET_SENTENCES = 260
TARGET_PARAGRAPHS = 140
GAME_PROBLEMS = 320
GAME_LEVELS = 10
GAME_PARAGRAPHS = 3
GAME_SENTENCES_PER_PARA = 3

# ---------------------------------------------------------------------------------------
# The sounds learners of Mandarin actually lose, and words that drill them.
# ---------------------------------------------------------------------------------------

WORD_GROUPS: list[tuple[str, list[str]]] = [
    ("zh / ch / sh — retroflex, tongue curled back", [
        "知道", "中国", "重要", "真的", "长城", "吃饭", "出去", "车站", "唱歌",
        "商店", "上课", "生日", "什么", "时间", "手机", "书店",
    ]),
    ("z / c / s — flat, tongue behind the teeth", [
        "早上", "杂志", "自己", "在家", "从来", "参加", "菜单", "词典",
        "三十", "四十", "岁数", "送给", "散步",
    ]),
    ("j / q / x — tongue flat, lips spread", [
        "见面", "今天", "机场", "简单", "介绍", "请问", "起来", "钱包",
        "青菜", "汽车", "谢谢", "学习", "西瓜", "希望", "现在", "小时",
    ]),
    ("ü — rounded lips, tongue forward", [
        "女儿", "绿色", "旅行", "去年", "需要", "学生", "月亮", "运动", "语言",
    ]),
    ("r — retroflex, not a rolled r", [
        "认识", "日本", "然后", "容易", "热情", "人们", "如果",
    ]),
    ("n / ng — where the tongue ends", [
        "很难", "面包", "banana", "安静", "因为", "英语", "朋友", "房间",
        "东西", "工作", "红色", "空气",
    ]),
    ("tone pairs that change meaning", [
        "妈妈", "麻烦", "马上", "骂人", "买卖", "报纸", "包子",
        "水果", "睡觉", "说话", "数学",
    ]),
    ("everyday words", [
        "你好", "再见", "谢谢", "对不起", "没关系", "老师", "同学", "朋友",
        "家人", "医生", "护士", "工人", "农民", "孩子", "爸爸",
        "哥哥", "姐姐", "弟弟", "妹妹", "爷爷", "奶奶",
    ]),
]

# "banana" slipped into the list above by accident in an earlier draft; drop anything
# that is not Chinese rather than letting it reach the lexicon.
WORD_GROUPS = [(f, [w for w in ws if all("一" <= c <= "鿿" for c in w)])
               for f, ws in WORD_GROUPS]

SUBJECTS = ["我", "你", "他", "她", "我们", "他们", "老师", "学生", "妈妈", "爸爸", "朋友"]

# Verbs live with their theme. A shared pool produced 学生没有喝房间 - "the student did not
# drink the room" - which is grammatical and meaningless, exactly the failure the English
# generator hit before its verbs were scoped.
THEMES: dict[str, dict] = {
    "学习": {
        "verbs": ["学习", "读", "看", "记得", "复习", "练习"],
        "objects": ["中文", "汉字", "课本", "生词", "语法", "发音", "作业", "英语",
                    "数学", "故事书"],
    },
    "食物": {
        "verbs": ["吃", "买", "做", "喜欢"],
        "objects": ["中国菜", "米饭", "面条", "水果", "青菜", "鸡蛋", "包子", "饺子"],
    },
    "饮料": {
        "verbs": ["喝", "买", "喜欢"],
        "objects": ["咖啡", "牛奶", "热茶", "果汁"],
    },
    "旅行": {
        "verbs": ["看", "找", "喜欢"],
        "objects": ["地图", "宾馆", "车站", "海边", "长城", "火车", "飞机", "行李"],
    },
    "工作": {
        "verbs": ["看", "找", "记得", "准备", "喜欢"],
        "objects": ["会议", "同事", "办公室", "电脑", "计划", "问题", "公司", "名片"],
    },
}

# 喜欢 is stative: 请喜欢咖啡 is not something anyone says.
STATIVE = {"喜欢", "记得"}

# (hanzi frame, pinyin frame, action_only)
#
# The pinyin is composed from the same slots rather than re-derived from the finished
# sentence. pypinyin guesses polyphonic readings from context and guessed inconsistently:
# 中文 came out zhōng wén in one sentence and zhòng wén in another. A learner reading the
# wrong tone off the screen is worse than no pinyin at all.
FRAMES: list[tuple[str, str, bool]] = [
    ("{s}{v}{o}。", "{s} {v} {o}", False),
    ("{s}每天{v}{o}。", "{s} měi tiān {v} {o}", False),
    ("{s}不{v}{o}。", "{s} bù {v} {o}", False),
    ("{s}很喜欢{o}。", "{s} hěn xǐ huān {o}", False),
    ("请{v}{o}。", "qǐng {v} {o}", True),
    ("{s}想{v}{o}吗？", "{s} xiǎng {v} {o} ma", True),
    ("{s}明天{v}{o}。", "{s} míng tiān {v} {o}", True),
    ("{s}已经{v}{o}了。", "{s} yǐ jīng {v} {o} le", True),
    ("{s}常常{v}{o}。", "{s} cháng cháng {v} {o}", False),
    ("{s}不想{v}{o}。", "{s} bù xiǎng {v} {o}", True),
]


def log(m: str) -> None:
    print(f"[content-zh] {m}", flush=True)


def to_pinyin(text: str) -> str:
    """Whole-string, so polyphonic characters get their contextual reading."""
    return " ".join(p[0] for p in pinyin(text, style=Style.TONE, errors="ignore"))


def is_hanzi(s: str) -> bool:
    return all("一" <= c <= "鿿" for c in s)


# ---------------------------------------------------------------------------------------

def build_words() -> list[tuple[str, str, str]]:
    out, seen = [], set()
    for focus, words in WORD_GROUPS:
        for w in words:
            if w in seen:
                continue
            seen.add(w)
            out.append((w, to_pinyin(w), focus))
    return out


def build_sentences(rng: random.Random) -> list[tuple[str, str, str, str, int]]:
    """@return (hanzi, pinyin, focus, theme, frame_index)"""
    combos = []
    for theme, spec in THEMES.items():
        for obj in spec["objects"]:
            for verb in spec["verbs"]:
                for fi in range(len(FRAMES)):
                    combos.append((theme, obj, verb, fi))
    rng.shuffle(combos)

    # One canonical reading per component, computed once and reused everywhere.
    canon = {w: to_pinyin(w) for w in
             set(SUBJECTS) | {v for s in THEMES.values() for v in s["verbs"]}
             | {o for s in THEMES.values() for o in s["objects"]}}

    out, seen = [], set()
    for theme, obj, verb, fi in combos:
        frame, py_frame, action_only = FRAMES[fi]
        if action_only and verb in STATIVE:
            continue

        subj = rng.choice(SUBJECTS)
        text = frame.format(s=subj, v=verb, o=obj)
        if text in seen:
            continue
        seen.add(text)

        py = py_frame.format(s=canon[subj], v=canon[verb], o=canon[obj])
        out.append((text, " ".join(py.split()), f"连读 · {theme}", theme, fi))
    return out


def build_paragraphs(sentences, rng, count) -> list[tuple[str, str, str]]:
    by_theme: dict[str, list[tuple[str, str, int]]] = {}
    for text, py, _, theme, fi in sentences:
        by_theme.setdefault(theme, []).append((text, py, fi))

    out, seen = [], set()
    themes = [t for t in by_theme if len(by_theme[t]) >= 3]
    attempts = 0
    while len(out) < count and attempts < count * 80:
        attempts += 1
        theme = rng.choice(themes)
        picked = rng.sample(by_theme[theme], 3)
        if len({fi for _, _, fi in picked}) < 3:
            continue
        text = "".join(t for t, _, _ in picked)
        if text in seen:
            continue
        seen.add(text)
        # Carry each sentence's pinyin through rather than re-deriving it from the joined text.
        py = " ".join(p for _, p, _ in picked)
        out.append((text, py, f"三句连读 · {theme}"))
    return out


def syllable_difficulty(hanzi: str, py: str) -> float:
    """Rough effort per syllable: retroflex, alveolo-palatal, ü and nasal finals cost most."""
    hard = ["zh", "ch", "sh", "r", "j", "q", "x", "z", "c", "s", "ü", "v", "ng"]
    score = sum(2 if h in py else 0 for h in ("zh", "ch", "sh", "r"))
    score += sum(1.5 if h in py else 0 for h in ("j", "q", "x"))
    score += sum(1 if h in py else 0 for h in ("z", "c", "s", "ng"))
    score += 2 if ("ü" in py or "v" in py) else 0
    return score / max(1, len(hanzi))


def build_game_problems(sentences, rng) -> list[tuple[int, str, str, list[str]]]:
    scored = [(syllable_difficulty(t, p), t, p, theme, fi) for t, p, _, theme, fi in sentences]
    scored.sort(key=lambda r: r[0])

    band = max(1, len(scored) // GAME_LEVELS)
    bands = [scored[i * band:(i + 1) * band] for i in range(GAME_LEVELS)]
    bands[-1].extend(scored[GAME_LEVELS * band:])

    per_level = GAME_PROBLEMS // GAME_LEVELS
    out, seen = [], set()

    for level in range(1, GAME_LEVELS + 1):
        pool = bands[level - 1]
        by_theme: dict[str, list[tuple[str, str, int]]] = {}
        for _, text, py, theme, fi in pool:
            by_theme.setdefault(theme, []).append((text, py, fi))
        themes = [t for t in by_theme if len(by_theme[t]) >= GAME_SENTENCES_PER_PARA * 2] \
            or list(by_theme)

        paragraphs_needed = GAME_PARAGRAPHS + (1 if level >= 7 else 0)
        needed = paragraphs_needed * GAME_SENTENCES_PER_PARA

        made, attempts = 0, 0
        while made < per_level and attempts < per_level * 300:
            attempts += 1
            theme = rng.choice(themes)
            available = by_theme[theme]
            if len(available) < needed:
                continue
            picked = rng.sample(available, needed)

            paras, pys, ok = [], [], True
            for p in range(paragraphs_needed):
                chunk = picked[p * GAME_SENTENCES_PER_PARA:(p + 1) * GAME_SENTENCES_PER_PARA]
                if len({fi for _, _, fi in chunk}) < GAME_SENTENCES_PER_PARA:
                    ok = False
                    break
                paras.append("".join(t for t, _, _ in chunk))
                pys.append(" ".join(p2 for _, p2, _ in chunk))
            if not ok:
                continue

            key = "||".join(paras)
            if key in seen:
                continue
            seen.add(key)
            out.append((level, f"{theme} · 第{level}级", "||".join(pys), paras))
            made += 1
    return out


# ---------------------------------------------------------------------------------------
# The pinyin table that replaces the A-Z section
# ---------------------------------------------------------------------------------------

INITIALS = [
    ("b", "爸", "unaspirated p"), ("p", "怕", "aspirated p"), ("m", "妈", "m"),
    ("f", "发", "f"), ("d", "大", "unaspirated t"), ("t", "他", "aspirated t"),
    ("n", "那", "n"), ("l", "来", "l"), ("g", "high", "unaspirated k"),
    ("k", "开", "aspirated k"), ("h", "好", "h, further back than English"),
    ("j", "见", "tongue flat, lips spread"), ("q", "去", "aspirated j"),
    ("x", "谢", "between English s and sh"),
    ("zh", "中", "retroflex, tongue curled back"), ("ch", "吃", "aspirated zh"),
    ("sh", "是", "retroflex sh"), ("r", "人", "retroflex, not rolled"),
    ("z", "早", "flat ts"), ("c", "菜", "aspirated z"), ("s", "三", "flat s"),
]
INITIALS = [(i, h, d) for i, h, d in INITIALS if is_hanzi(h)]

FINALS = [
    ("a", "大"), ("o", "我"), ("e", "饿"), ("i", "一"), ("u", "五"), ("ü", "女"),
    ("ai", "爱"), ("ei", "杯"), ("ao", "好"), ("ou", "口"),
    ("an", "安"), ("en", "很"), ("ang", "忙"), ("eng", "冷"), ("ong", "东"),
    ("ia", "家"), ("ie", "谢"), ("iao", "小"), ("iu", "六"), ("ian", "天"),
    # 熊 is the usual -iong example but espeak returns nothing the model can emit for it,
    # so it would sit in the table unscoreable. 穷 carries the same final.
    ("in", "新"), ("iang", "两"), ("ing", "明"), ("iong", "穷"),
    ("ua", "花"), ("uo", "国"), ("uai", "快"), ("ui", "水"), ("uan", "关"),
    ("un", "问"), ("uang", "黄"), ("üe", "月"), ("üan", "元"), ("ün", "云"),
]

TONES = [
    ("1", "妈", "high and level"),
    ("2", "麻", "rising, like a question"),
    ("3", "马", "dips down then rises"),
    ("4", "骂", "sharp fall"),
]


def build_syllables() -> list[tuple[str, str, str, str, str]]:
    """@return (kind, symbol, example hanzi, example pinyin, note)"""
    rows = []
    for sym, han, note in INITIALS:
        rows.append(("INITIAL", sym, han, to_pinyin(han), note))
    for sym, han in FINALS:
        rows.append(("FINAL", sym, han, to_pinyin(han), ""))
    for sym, han, note in TONES:
        rows.append(("TONE", sym, han, to_pinyin(han), note))
    return rows


# ---------------------------------------------------------------------------------------

def main() -> None:
    rng = random.Random(SEED)
    ASSETS.mkdir(parents=True, exist_ok=True)

    words = build_words()
    log(f"words: {len(words)}")

    sentences = build_sentences(rng)
    log(f"sentences: {len(sentences)} generated")

    paragraphs = build_paragraphs(sentences, rng, TARGET_PARAGRAPHS)
    log(f"paragraphs: {len(paragraphs)}")

    problems = build_game_problems(sentences, rng)
    log(f"game problems: {len(problems)}")

    kept_sentences = sentences[:TARGET_SENTENCES]

    rows = [("WORD", h, p, f) for h, p, f in words]
    rows += [("SENTENCE", h, p, f) for h, p, f, _, _ in kept_sentences]
    rows += [("PARAGRAPH", h, p, f) for h, p, f in paragraphs]

    out = ASSETS / "prompts_zh.tsv"
    with out.open("w", encoding="utf-8", newline="\n") as fh:
        for unit, hanzi, py, focus in rows:
            fh.write(f"{unit}\t{hanzi}\t{py}\t{focus}\n")
    log(f"wrote {out.name}: {len(rows)} prompts")

    games = ASSETS / "game_problems_zh.tsv"
    with games.open("w", encoding="utf-8", newline="\n") as fh:
        for level, title, py, paras in problems:
            fh.write(f"{level}\t{title}\t{py}\t{'||'.join(paras)}\n")
    per_level = Counter(l for l, _, _, _ in problems)
    log(f"wrote {games.name}: " + "  ".join(f"L{k}={per_level[k]}" for k in sorted(per_level)))

    syl = ASSETS / "zh_syllables.tsv"
    with syl.open("w", encoding="utf-8", newline="\n") as fh:
        for kind, sym, han, py, note in build_syllables():
            fh.write(f"{kind}\t{sym}\t{han}\t{py}\t{note}\n")
    log(f"wrote {syl.name}: {len(build_syllables())} rows")

    chars = {c for _, h, _, _ in rows for c in h if "一" <= c <= "鿿"}
    chars |= {c for _, _, _, paras in problems for p in paras for c in p
              if "一" <= c <= "鿿"}
    chars |= {h for _, _, h, _, _ in build_syllables()}
    log(f"distinct characters used: {len(chars)}")
    (ROOT / "tools" / "zh_charset.txt").write_text("".join(sorted(chars)), encoding="utf-8")
    log("wrote tools/zh_charset.txt — feed it to tools/build_lexicon_zh.py")


if __name__ == "__main__":
    main()
