# Packages everything needed to build and run this project on a machine with no internet.
#
#   .\tools\make-offline-bundle.ps1 -Destination C:\pronunciation-offline
#
#   -Tier 1   build the app and install it to a phone        (~1.7 GB)
#   -Tier 2   + regenerate models, lexicons and content      (~4.5 GB)
#   -Tier 3   + run the emulator                             (~13 GB)
#
# Run it on a machine where the build already works. It writes a restore.ps1 next to the
# payload; run that on the target. Nothing in the restore step touches the network.
#
# Deliberately NOT copied:
#   ~\.android\avd   disposable, ~9 GB, recreated by avdmanager in seconds
#   app\build        regenerated by the first build
#   .git             history is not needed to build

param(
    [Parameter(Mandatory = $true)][string]$Destination,
    [ValidateSet(1, 2, 3)][int]$Tier = 3
)

$ErrorActionPreference = "Stop"
$home_ = $env:USERPROFILE
$project = (Resolve-Path "$PSScriptRoot\..").Path

function Step($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Warn($m) { Write-Host "    $m" -ForegroundColor Yellow }

# A live Gradle daemon holds locks inside ~\.gradle and makes the copy fail partway.
Step "Stopping any Gradle daemon so its files are not locked"
Push-Location $project
if (Test-Path ".\gradlew.bat") {
    $env:JAVA_HOME = "C:\Android\jdk17"
    & .\gradlew.bat --stop 2>&1 | Out-Null
}
Pop-Location

# name, source, relative destination, minimum tier, excluded subdirectories
$items = @(
    @{ n = "Project + assets";   s = $project;                                d = "project";                     t = 1; x = @("build", ".git", ".gradle", ".idea") }
    @{ n = "JDK 17";             s = "C:\Android\jdk17";                      d = "Android\jdk17";               t = 1; x = @() }
    @{ n = "SDK platform-tools"; s = "C:\Android\Sdk\platform-tools";         d = "Android\Sdk\platform-tools";  t = 1; x = @() }
    @{ n = "SDK platforms";      s = "C:\Android\Sdk\platforms";              d = "Android\Sdk\platforms";       t = 1; x = @() }
    @{ n = "SDK build-tools";    s = "C:\Android\Sdk\build-tools";            d = "Android\Sdk\build-tools";     t = 1; x = @() }
    @{ n = "SDK licences";       s = "C:\Android\Sdk\licenses";               d = "Android\Sdk\licenses";        t = 1; x = @() }
    @{ n = "Gradle distribution"; s = "$home_\.gradle\wrapper\dists";         d = "gradle-home\wrapper\dists";   t = 1; x = @() }
    # modules-2 only. The sibling caches are regenerable, add ~700 MB, and the daemon locks
    # some of them.
    @{ n = "Gradle dep cache";   s = "$home_\.gradle\caches\modules-2";       d = "gradle-home\caches\modules-2"; t = 1; x = @() }

    @{ n = "Python + packages";  s = "C:\Android\python312";                  d = "Android\python312";           t = 2; x = @() }
    @{ n = "espeak-ng";          s = "C:\Android\espeak";                     d = "Android\espeak";              t = 2; x = @() }
    @{ n = "HuggingFace cache";  s = "$home_\.cache\huggingface";             d = "hf-cache";                    t = 2; x = @() }
    @{ n = "SDK cmdline-tools";  s = "C:\Android\Sdk\cmdline-tools";          d = "Android\Sdk\cmdline-tools";   t = 2; x = @() }
    @{ n = "Portable git";       s = "C:\Android\git";                        d = "Android\git";                 t = 2; x = @() }
    @{ n = "Gradle binary";      s = "C:\Android\gradle";                     d = "Android\gradle";              t = 2; x = @() }

    @{ n = "Emulator";           s = "C:\Android\Sdk\emulator";               d = "Android\Sdk\emulator";        t = 3; x = @() }
    @{ n = "System images";      s = "C:\Android\Sdk\system-images";          d = "Android\Sdk\system-images";   t = 3; x = @() }
)

$selected = $items | Where-Object { $_.t -le $Tier }

Step "Checking sources"
foreach ($m in ($selected | Where-Object { -not (Test-Path $_.s) })) {
    Warn "missing, will skip: $($m.n)  [$($m.s)]"
}
$selected = $selected | Where-Object { Test-Path $_.s }

$total = 0
foreach ($i in $selected) {
    $i.bytes = (Get-ChildItem $i.s -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $i.x.Count -eq 0 -or $_.FullName -notmatch ("\\(" + ($i.x -join "|") + ")\\") } |
        Measure-Object Length -Sum).Sum
    $total += $i.bytes
}
Write-Host ("    tier {0}: {1} components, {2:N0} MB" -f $Tier, $selected.Count, ($total / 1MB))

New-Item -ItemType Directory -Force $Destination | Out-Null
$free = (Get-PSDrive ((Get-Item $Destination).PSDrive.Name)).Free
if ($free -lt $total * 1.05) {
    throw ("Not enough space at {0}: need {1:N0} MB, have {2:N0} MB" -f $Destination, ($total / 1MB), ($free / 1MB))
}

foreach ($i in $selected) {
    Step ("Copying {0} ({1:N0} MB)" -f $i.n, ($i.bytes / 1MB))
    $target = Join-Path $Destination $i.d
    New-Item -ItemType Directory -Force $target | Out-Null

    # robocopy is dramatically faster than Copy-Item for many small files.
    # /XF *.lock skips Gradle's lock files, which are transient and often held open.
    $args = @($i.s, $target, "/E", "/XF", "*.lock", "/NFL", "/NDL", "/NJH", "/NJS", "/NP", "/R:1", "/W:1")
    if ($i.x.Count) { $args += @("/XD") + $i.x }
    robocopy @args | Out-Null
    # robocopy exit codes are bit flags; anything under 8 is success.
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed for $($i.n) (exit $LASTEXITCODE)" }
}

# --- restore script written into the bundle --------------------------------------------
$restore = @'
# Restores this bundle onto an offline machine. Run from inside the bundle folder.
#
#   .\restore.ps1                                  # project goes to C:\pronunciation-app
#   .\restore.ps1 -ProjectDir D:\work\pronunciation
#
# No admin rights and no network. Everything lands under C:\Android plus your user profile.

param([string]$ProjectDir = "C:\pronunciation-app")

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$home_ = $env:USERPROFILE

function Step($m) { Write-Host "==> $m" -ForegroundColor Cyan }

if (Test-Path "$root\Android") {
    Step "Toolchain -> C:\Android"
    robocopy "$root\Android" "C:\Android" /E /NFL /NDL /NJH /NJS /NP | Out-Null
}
if (Test-Path "$root\gradle-home") {
    Step "Gradle cache -> $home_\.gradle"
    robocopy "$root\gradle-home" "$home_\.gradle" /E /NFL /NDL /NJH /NJS /NP | Out-Null
}
if (Test-Path "$root\hf-cache") {
    Step "HuggingFace cache -> $home_\.cache\huggingface"
    robocopy "$root\hf-cache" "$home_\.cache\huggingface" /E /NFL /NDL /NJH /NJS /NP | Out-Null
}
if (Test-Path "$root\project") {
    Step "Project -> $ProjectDir"
    robocopy "$root\project" $ProjectDir /E /NFL /NDL /NJH /NJS /NP | Out-Null
}

Step "Environment variables (user scope)"
[Environment]::SetEnvironmentVariable("JAVA_HOME", "C:\Android\jdk17", "User")
[Environment]::SetEnvironmentVariable("ANDROID_HOME", "C:\Android\Sdk", "User")
[Environment]::SetEnvironmentVariable("ESPEAK_DATA_PATH", "C:\Android\espeak\eSpeak NG\espeak-ng-data", "User")
$add = @("C:\Android\jdk17\bin", "C:\Android\Sdk\platform-tools", "C:\Android\Sdk\emulator")
$cur = [Environment]::GetEnvironmentVariable("Path", "User")
if ($null -eq $cur) { $cur = "" }
$parts = @($cur -split ';' | Where-Object { $_ -ne '' })
foreach ($p in $add) { if ($parts -notcontains $p) { $parts += $p } }
[Environment]::SetEnvironmentVariable("Path", ($parts -join ';'), "User")

# local.properties is machine-specific and gitignored, so it is written rather than copied.
Step "Pointing the project at the SDK"
Set-Content -Path (Join-Path $ProjectDir "local.properties") `
    -Value "sdk.dir=C\:\\Android\\Sdk" -Encoding ascii

Write-Host ""
Write-Host "Restored. Open a NEW terminal, then:" -ForegroundColor Green
Write-Host "  cd $ProjectDir"
Write-Host "  .\gradlew.bat assembleDebug --offline"
Write-Host ""
Write-Host "To run it on the emulator you still need a one-time admin step plus a reboot:" -ForegroundColor Yellow
Write-Host "  dism /online /Enable-Feature /FeatureName:HypervisorPlatform /All /NoRestart"
Write-Host "Then recreate an AVD (instances are not shipped in this bundle):"
Write-Host '  avdmanager create avd -n android8 -k "system-images;android-26;google_apis;x86_64" -d pixel_2'
Write-Host "  .\tools\run-emulator.ps1 -Avd android8"
Write-Host ""
Write-Host "The generated model and lexicon are already inside the project's assets folder," -ForegroundColor Green
Write-Host "so no regeneration and no network is needed to build."
'@
Set-Content -Path (Join-Path $Destination "restore.ps1") -Value $restore -Encoding utf8

$manifest = $selected | ForEach-Object { "{0,9:N0} MB  {1}" -f ($_.bytes / 1MB), $_.n }
Set-Content -Path (Join-Path $Destination "MANIFEST.txt") `
    -Value (@("Offline bundle - tier $Tier", "") + $manifest +
        @("", ("{0,9:N0} MB  TOTAL" -f ($total / 1MB)))) -Encoding utf8

Write-Host ""
Write-Host ("Bundle ready at {0} ({1:N0} MB)" -f $Destination, ($total / 1MB)) -ForegroundColor Green
Write-Host "Move it to the offline machine and run restore.ps1 there."

# robocopy sets a non-zero exit code even on success (1 = files copied), which makes callers
# and CI think the script failed. Clear it.
$global:LASTEXITCODE = 0
exit 0
