# Packages this machine's working toolchain into a folder you can carry to an offline machine.
#
#   .\tools\make-offline-bundle.ps1 -Destination D:\offline-bundle -Tier 1
#
#   Tier 1  build the app + install to a phone   (~1.4 GB)
#   Tier 2  + regenerate the model offline       (~2.7 GB)
#   Tier 3  + run the emulator                   (~8 GB)
#
# Run it on a machine where the build already works. It writes a restore.ps1 alongside the
# payload; run that on the target.
#
# Deliberately NOT copied: ~\.android\avd (disposable, 9 GB - recreate with avdmanager) and
# app\build (regenerated by the first build).

param(
    [Parameter(Mandatory = $true)][string]$Destination,
    [ValidateSet(1, 2, 3)][int]$Tier = 1
)

$ErrorActionPreference = "Stop"
$home_ = $env:USERPROFILE

function Step($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Warn($m) { Write-Host "    $m" -ForegroundColor Yellow }

# A live Gradle daemon holds locks inside ~\.gradle and makes the copy fail partway.
Step "Stopping any Gradle daemon so its files are not locked"
if (Test-Path ".\gradlew.bat") {
    $env:JAVA_HOME = "C:\Android\jdk17"
    & .\gradlew.bat --stop 2>&1 | Out-Null
}

# name, source, relative destination, minimum tier
$items = @(
    @{ n = "JDK 17";              s = "C:\Android\jdk17";                    d = "Android\jdk17";                    t = 1 }
    @{ n = "SDK platform-tools";  s = "C:\Android\Sdk\platform-tools";       d = "Android\Sdk\platform-tools";       t = 1 }
    @{ n = "SDK platforms";       s = "C:\Android\Sdk\platforms";            d = "Android\Sdk\platforms";            t = 1 }
    @{ n = "SDK build-tools";     s = "C:\Android\Sdk\build-tools";          d = "Android\Sdk\build-tools";          t = 1 }
    @{ n = "SDK licences";        s = "C:\Android\Sdk\licenses";             d = "Android\Sdk\licenses";             t = 1 }
    @{ n = "Gradle distribution"; s = "$home_\.gradle\wrapper\dists";        d = "gradle-home\wrapper\dists";        t = 1 }
    # modules-2 only. The sibling caches (build-cache-1, transforms-*, jars-*) are regenerable
    # and add ~700 MB, and the daemon holds locks on some of them.
    @{ n = "Gradle dep cache";    s = "$home_\.gradle\caches\modules-2";     d = "gradle-home\caches\modules-2";     t = 1 }
    @{ n = "Model assets";        s = "app\src\main\assets";                 d = "project-assets";                   t = 1 }
    @{ n = "Python + packages";   s = "C:\Android\python312";                d = "Android\python312";                t = 2 }
    @{ n = "HuggingFace cache";   s = "$home_\.cache\huggingface";           d = "hf-cache";                         t = 2 }
    @{ n = "CMUdict cache";       s = "tools\.cache";                        d = "tools-cache";                      t = 2 }
    @{ n = "Emulator";            s = "C:\Android\Sdk\emulator";             d = "Android\Sdk\emulator";             t = 3 }
    @{ n = "System images";       s = "C:\Android\Sdk\system-images";        d = "Android\Sdk\system-images";        t = 3 }
    @{ n = "SDK cmdline-tools";   s = "C:\Android\Sdk\cmdline-tools";        d = "Android\Sdk\cmdline-tools";        t = 3 }
    @{ n = "Portable git";        s = "C:\Android\git";                      d = "Android\git";                      t = 3 }
)

$selected = $items | Where-Object { $_.t -le $Tier }

Step "Checking sources"
$missing = $selected | Where-Object { -not (Test-Path $_.s) }
foreach ($m in $missing) { Warn "missing, will skip: $($m.n)  [$($m.s)]" }
$selected = $selected | Where-Object { Test-Path $_.s }

$total = 0
foreach ($i in $selected) {
    $i.bytes = (Get-ChildItem $i.s -Recurse -File -ErrorAction SilentlyContinue |
        Measure-Object Length -Sum).Sum
    $total += $i.bytes
}
Write-Host ("    tier {0}: {1} components, {2:N0} MB" -f $Tier, $selected.Count, ($total / 1MB))

New-Item -ItemType Directory -Force $Destination | Out-Null
$free = (Get-PSDrive ((Get-Item $Destination).PSDrive.Name)).Free
if ($free -lt $total * 1.05) {
    throw ("Not enough space at {0}: need {1:N0} MB, have {2:N0} MB" -f $Destination, ($total / 1MB), ($free / 1MB))
}

foreach ($i in $selected) {
    Step ("Copying {0} ({1:N0} MB)" -f $i.n, ($i.bytes / 1MB))
    $target = Join-Path $Destination $i.d
    New-Item -ItemType Directory -Force $target | Out-Null
    # robocopy is dramatically faster than Copy-Item for many small files.
    # /XF *.lock skips Gradle's lock files, which are transient and often held open.
    robocopy $i.s $target /E /XF *.lock /NFL /NDL /NJH /NJS /NP /R:1 /W:1 | Out-Null
    # robocopy exit codes are bit flags; anything under 8 is success.
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed for $($i.n) (exit $LASTEXITCODE)" }
}

# --- restore script written into the bundle --------------------------------------------
$restore = @'
# Restores this bundle onto an offline machine. Run from inside the bundle folder.
#
#   .\restore.ps1
#
# Copies the toolchain to C:\Android and the Gradle cache to your user profile, then sets
# JAVA_HOME / ANDROID_HOME / PATH at user scope. No admin required. No network used.

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$home_ = $env:USERPROFILE

function Step($m) { Write-Host "==> $m" -ForegroundColor Cyan }

if (Test-Path "$root\Android") {
    Step "Toolchain -> C:\Android"
    robocopy "$root\Android" "C:\Android" /E /NFL /NDL /NJH /NJS /NP | Out-Null
}
if (Test-Path "$root\gradle-home") {
    Step "Gradle cache -> $home_\.gradle"
    robocopy "$root\gradle-home" "$home_\.gradle" /E /NFL /NDL /NJH /NJS /NP | Out-Null
}
if (Test-Path "$root\hf-cache") {
    Step "HuggingFace cache -> $home_\.cache\huggingface"
    robocopy "$root\hf-cache" "$home_\.cache\huggingface" /E /NFL /NDL /NJH /NJS /NP | Out-Null
}

Step "Environment variables (user scope)"
[Environment]::SetEnvironmentVariable("JAVA_HOME", "C:\Android\jdk17", "User")
[Environment]::SetEnvironmentVariable("ANDROID_HOME", "C:\Android\Sdk", "User")
$add = @("C:\Android\jdk17\bin", "C:\Android\Sdk\platform-tools", "C:\Android\Sdk\emulator")
$cur = [Environment]::GetEnvironmentVariable("Path", "User")
if ($null -eq $cur) { $cur = "" }
$parts = @($cur -split ';' | Where-Object { $_ -ne '' })
foreach ($p in $add) { if ($parts -notcontains $p) { $parts += $p } }
[Environment]::SetEnvironmentVariable("Path", ($parts -join ';'), "User")

Write-Host ""
Write-Host "Restored. Remaining steps:" -ForegroundColor Green
Write-Host "  1. Clone or copy the project, then copy project-assets\* into"
Write-Host "     <project>\app\src\main\assets\   (the model is not in git)"
Write-Host "  2. Point the project at the SDK - create <project>\local.properties containing:"
Write-Host "       sdk.dir=C\:\\Android\\Sdk"
Write-Host "  3. Open a NEW terminal, then verify with no network:"
Write-Host "       .\gradlew.bat assembleDebug --offline"
Write-Host ""
Write-Host "For the emulator you still need an admin step plus a reboot:" -ForegroundColor Yellow
Write-Host "  dism /online /Enable-Feature /FeatureName:HypervisorPlatform /All /NoRestart"
Write-Host "Then recreate an AVD (avd instances are not shipped in this bundle):"
Write-Host "  avdmanager create avd -n android8 -k ""system-images;android-26;google_apis;x86_64"" -d pixel_2"
'@
Set-Content -Path (Join-Path $Destination "restore.ps1") -Value $restore -Encoding utf8

$manifest = $selected | ForEach-Object { "{0,8:N0} MB  {1}" -f ($_.bytes / 1MB), $_.n }
Set-Content -Path (Join-Path $Destination "MANIFEST.txt") `
    -Value (@("Offline bundle - tier $Tier", "") + $manifest +
        @("", ("{0,8:N0} MB  TOTAL" -f ($total / 1MB)))) -Encoding utf8

Write-Host ""
Write-Host ("Bundle ready at {0} ({1:N0} MB)" -f $Destination, ($total / 1MB)) -ForegroundColor Green
Write-Host "Zip it, move it, then run restore.ps1 on the offline machine."

# robocopy sets a non-zero exit code even on success (1 = files copied), which makes callers
# and CI think the script failed. Clear it.
$global:LASTEXITCODE = 0
exit 0
